global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'mymachine'
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']
  - job_name: 'machine'
    static_configs:
    - targets: ['192.168.31.40:9100']
